import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from "./AuthProvider/page";

export const metadata: Metadata = {
  title: "Next SQL",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col">
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
